### ISSUE TITLE
I don't understand why it is so difficult for developers to install it using the <Add package form git URL>method?

### ISSUE THREAD

**Issue by ChensLance** [readyplayerme/rpm-unity-sdk-core#101]
It takes me 3-5 hours to install it. Could you provide another way to install it? For example: <Add package from disk...><Addpackage from tarball...>
![image](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/106513833/07be8967-e39a-487a-9d71-a59c12992d54)

**Comment by HarrisonHough** [comment]
There are currently no plans to change or add alternative ways to install the plugin. If we see a significant need for alternative ways to install the package, then we will consider it.
