### ISSUE TITLE
Reload Domain endless loop when selecting Dedicated Linux Server as build target

### ISSUE THREAD

**Issue by QF-David** [readyplayerme/rpm-unity-sdk-core#134]
Unity enters a endless lopp of domain reloading once the build target is switchted to dedicated server with Linux as the target platform.

**To Reproduce**
1. Setup new unity project (version: 2022.3.11f1, older versions might be affected as well)
2. Import rpm-unity-sdk-core git via package manager
3. Switch platform in Build Settings to Dedicated Server with Linux as target platform

**Expected behavior**
After the switch, once compilation is completed, Unity should be stuck in en endless loop of domain reloads.

**Desktop (please complete the following information):**
 - Ready Player Me Core version: 3.3.0
 - Ready Player Me WebView version: 2.0.0
 - glTFast version: 5.0.0
 - Unity Editor version: 2022.3.11f1
 - Operating System: Windows 11
 - Platform: Dedicated Server Linux

**Comment by HarrisonHough** [comment]
Can you check if these two define symbols have been added to Dedicated server build target?
And add them if they are not? 
![image](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/7085672/c9c6255a-e08f-4b16-babd-c1c58eca9bf9)

**Comment by QF-David** [comment]
Thanks for the quick response. The define symbols where not present and adding them fixed the issue as you suggested. Thanks a lot!
