### ISSUE TITLE
No suitable method found to override

### ISSUE THREAD

**Issue by moninm** [readyplayerme/rpm-unity-sdk-core#156]
**Describe the bug**
Here is the error :

Library/PackageCache/com.readyplayerme.core@d0d0d02bab/Runtime/GLTF/GltFastGameObjectInstantiator.cs(24,30): error CS0115: 'GltFastGameObjectInstantiator.AddPrimitive(uint, string, Mesh, int[], uint[], uint?, float[], int)': no suitable method found to override

**To Reproduce**
1. Install Ready Player Me Core version 4.0.1
2. Install GLTFast version 6.0.1
4. See compile error in the console

**Expected behavior**
No compile error

**Desktop (please complete the following information):**
 - Ready Player Me Core version : 4.0.1
 - glTFast version : 6.0.1
 - Unity Editor version : 2021.3.32f1
 - Render Pipeline and version : 12.1.13
 - Operating System : Mac
 - Platform: all

**Comment by HarrisonHough** [comment]
Hey there. 
Thanks for reporting. We are aware of the issue, it is related to a breaking change in glTFast v6.0. 
We will include a fix in our next release. 
For the time being you can downgrade to any 5.x version until we are able to finalize our next release.

**Comment by moninm** [comment]
Ok thank you
