### ISSUE TITLE
RPM Not working in Unity IOS 

### ISSUE THREAD

**Issue by AtulAbhiwan03** [readyplayerme/rpm-unity-sdk-core#165]
I am using the Avatar creator sample in unity version 2020.3.15f1 and IOS version 17 but it is showing error for GenderTypeConversion and also the error is not specified and when i try to create the avatar again it is showing the Forbidden error.

**Comment by HarrisonHough** [comment]
Try adjusting the Managed Stripping level setting in the player settings. 
If possible try set them to disabled or minimal. The options may differ however depending on Unity Version. 

![image](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/7085672/02bf7294-742e-41b8-b9fe-4681364de14f)

**Comment by HarrisonHough** [comment]
closing

**Comment by Kushulain** [comment]
This also happen on Android (Unity 2019.3.24 / IL2CPP Build / v5.0.0)

I also had different problem related to Code Stripping in PC Build (both mono & IL2CPP) leading to this popup message in the legacy Avatar Creator:
> "We failed to load the photo (we bet you look great, though)! Please try using a different file."

If you still want to fix this problem and benefit from code stripping, best solution is this:

Add a "link.xml" file inside "YourUnityProjectFolder/Assets/" with content:

```
<linker>
  <assembly fullname="ReadyPlayerMe.AvatarCreator" preserve="all" />
  <assembly fullname="ReadyPlayerMe.Core" preserve="all" />
</linker>
```

If you want to be sure it works: search for every "*.asmdef" files inside your readyplayerme package, in the case assembly changes in the future, and ensure they are all present in the link.xml.
But only these two assemblies fixed the problem for me.

see [Unity Code Stripping doc](https://docs.unity3d.com/Manual/ManagedCodeStripping.html) for more info
