### ISSUE TITLE
[BUG] Every time the Unity project is opened the CoreSettings asset is reset to defaults

### ISSUE THREAD

**Issue by FejZa** [readyplayerme/rpm-unity-sdk-core#201]
**Describe the bug**

Every time I open the Unity project with the Core SDK package the CoreSettings asset is reset to defaults and I am being prompted
to reconfigure domain and app ID.
I fix it by reverting the changes in git but next time I open the project it will happen again.

**Files**

![image](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/9565734/80a794b3-e849-4982-ab74-2e8c999cf001)

**Comment by HarrisonHough** [comment]
Can you share the following details: 
- Ready Player Me Core package version
- Unity Engine version
- Target platform
- Operating system you are using for running the editor (Mac, Windows, Linux)

And any other information that you think might be helpful for us to try and replicate the issue.

**Comment by FejZa** [comment]
This was on v4.1.2 using Unity 2023.2.4f1

I have new details on this issue. It does not happen every time the project is opened but when it is opened the first time after a fresh clone. So essentially if the Library folder is not generated yet for the project.

**Comment by HarrisonHough** [comment]
> This was on v4.1.2 using Unity 2023.2.4f1
> 
> I have new details on this issue. It does not happen every time the project is opened but when it is opened the first time after a fresh clone. So essentially if the Library folder is not generated yet for the project.

Thanks for the info, that is actually quite helpful. 
Is it on any particular operating system? 
Or perhaps on a build server?

**Comment by HarrisonHough** [comment]
This should be fixed in the upcoming 6.0 release

**Comment by FejZa** [comment]
Awesome. I'll retest and confirm, once we updated.

**Comment by HarrisonHough** [comment]
6.0 release is available now and should fix the issue. Please reopen this issue or let us know if it is still causing problems.
