### ISSUE TITLE
Undefined Symbols Error in iOS Build with Unity SDK

### ISSUE THREAD

**Issue by amokto** [readyplayerme/rpm-unity-sdk-core#205]
**Describe the bug**
When attempting to build an iOS project using the latest Unity SDK, an 'Undefined symbols' error occurs, specifically related to WebView components. This issue prevents successful iOS builds, hindering development and deployment on iOS devices.

**Files**
No specific .glb files or avatar URLs are linked to this issue.
The bug is reproducible in a new, empty Unity project with the latest SDK version.
Example scenes from the SDK have been tested without resolving the issue.

**To Reproduce**

1. Create a new Unity project.
2. Add the latest Unity SDK from the provided Git URL.
3. Add any sample using WebView (ie: AvatarCreatorSamples)
4. Attempt to build the project for iOS.
Encounter the 'Undefined symbols' error related to WebView.

**Expected behavior**
The expected behavior is a successful build for iOS without encountering the 'Undefined symbols' error.

**Screenshots**
<img width="554" alt="image" src="https://github.com/readyplayerme/rpm-unity-sdk-core/assets/103036086/644f6d6e-7437-40ac-afd6-46f884824839">

**Desktop (please complete the following information):**
 - Ready Player Me Core version: 4.1.2
 - Ready Player Me Avatar Loader version: N/A
 - Ready Player Me WebView version: 2.0.0
 - glTFast version: 5.0.0
 - Unity Editor version: 2022.3.10f1
 - Render Pipeline and version: Built-in, URP or HDRP (does not matter)
 - Operating System: MacOS Sonoma 14.1.1
 - Platform: iOS
 
additionally (if significant for the bug):

 - Device: iPhone11
 - OS: iOS 16.1.1

**Additional context**
Error Log

ld: Undefined symbols:
  _OBJC_CLASS_$_WKProcessPool, referenced from:
       in WebView.o
  _OBJC_CLASS_$_WKUserContentController, referenced from:
       in WebView.o
  _OBJC_CLASS_$_WKUserScript, referenced from:
       in WebView.o
  _OBJC_CLASS_$_WKWebView, referenced from:
       in WebView.o
      __OBJC_$_CATEGORY_WKWebView_$_WebViewProtocolConformed in WebView.o
  _OBJC_CLASS_$_WKWebViewConfiguration, referenced from:
       in WebView.o
  _OBJC_CLASS_$_WKWebsiteDataStore, referenced from:
       in WebView.o
  _WKWebsiteDataTypeDiskCache, referenced from:
      -[CWebViewPlugin clearCache:] in WebView.o
  _WKWebsiteDataTypeMemoryCache, referenced from:
      -[CWebViewPlugin clearCache:] in WebView.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by HarrisonHough** [comment]
Hey thanks for making the bug report. 

Can you try updating WebView to the latest version 2.1.2 and see if that fixes the issue?

**Comment by amokto** [comment]
I did try the newest version (2.1.2) as well and that has the same missing symbol error.

**Comment by soriac** [comment]
Having the same issue, trying to build both on iPhone and iPad

**Comment by redStriker** [comment]
Team, same issue here as well. Please let us know if this issue can be quickly fixed. Thank you!!

**Comment by redStriker** [comment]
It is working for me now. 

Make sure that you have the necessary frameworks linked in your Xcode project. In this case, it looks like you need to link the WebKit framework. To do this:

Open your Xcode project.
In the Project Navigator, select your project.
Go to the "General" tab.
Scroll down to the "Frameworks, Libraries, and Embedded Content" section.
Click the "+" button and add the WebKit framework.

**Comment by HarrisonHough** [comment]
Thanks for the update. WE do have a build process that is supposed to add the WebKit framework however it seems that it is not working as expected. Will investigate and work on a fix.

**Comment by HarrisonHough** [comment]
THis should be fixed in latest release 
https://github.com/readyplayerme/rpm-unity-sdk-webview/releases/tag/v2.1.3

Please let us know if that is not the case.
