### ISSUE TITLE
AvatarRenderLoader texture offset

### ISSUE THREAD

**Issue by FejZa** [readyplayerme/rpm-unity-sdk-core#237]
I am using the RPM Core Unity SDK v5 and the `AvatarRenderLoader` in Unity 2023.2.10f1

I am passing e.g. the following URL to the render loader:
https://models.readyplayer.me/6594816144c97659297f3948.glb

and using default render settings, like so:
`avatarRenderLoader.LoadRender(avatarUrl, new AvatarRenderSettings());`

It reports success and the returned texture looks like this:
![image](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/9565734/6ba024ab-952b-42d1-9a26-dbb0ba52d8c5)

This issue is reproduced using all our avatars.
Querying a 2D render for the same avatar using the Web API with:
https://models.readyplayer.me/6594816144c97659297f3948.png

works great.

**Comment by HarrisonHough** [comment]
Thanks for letting us know, we have released a hotfix for this. If you update to v6.0.1 you can set the RenderPose to None (which is the default value) and it should work as before. 

Let us know if you have any further issues.
