### ISSUE TITLE
JSON exception in class BodyTypeConverter

### ISSUE THREAD

**Issue by FiveMM** [readyplayerme/rpm-unity-sdk-core#240]
Getting this exception when trying to load an avatar : "Expected string value, instead found: Integer".
Getting the error in Editor and browsers.

Model : https://models.readyplayer.me/65d5ae4662ad266c2e91f3ae.glb
SDK version : 6.0.0
Unity version : 2021.3.19f1
Browser : Firefox (123.0 (64-bit)) and Edge (105.0.1343.53 (Official build) (64-bit))

Current solution is to add "return BodyType.FullBody;" to the top of the "ReadJson" method of the class. I am only using FullBody avatars so not an issue for me.

**Comment by HarrisonHough** [comment]
I'm unable to replicate the issue. When exactly does the issue occur, is it when loading an avatar via the Avatar creator? 
And what have you set the Managed Stripping Level to in your player settings? 
![image](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/7085672/c0ad98ec-772b-4f51-bb77-8a045c899a4d)

**Comment by FiveMM** [comment]
Managed stripping level is "Low", but that shouldn't matter as I am getting the issue in the Editor as well.
I am loading the avatar using the Avatar Loader from Tools\Read Player Me\Avatar Loader in the Editor.
I also tried using the Sample files and loading it in runtime by getting it's URL from the inspector field "customAvatarURL".
I added this field and a method to load the avatar which I call from a button in the UI.
You can reproduce the result by starting a new project, importing the core sdk and the webgl sample and replacing the WebGLAvatarLoader.cs with the following code

```csharp

using ReadyPlayerMe.Core;
using UnityEngine;
using BodyType = ReadyPlayerMe.Core.BodyType;


[RequireComponent(typeof(WebFrameHandler))]
public class WebGLAvatarLoader : MonoBehaviour
{
    private const string TAG = nameof(WebGLAvatarLoader);
    private GameObject avatar;
    private string avatarUrl = "";
    private WebFrameHandler webFrameHandler;
    [SerializeField] private string customAvatarUrl = "";
    public void LoadCustom()
    {
        HandleAvatarLoaded(customAvatarUrl);
    }

    private void Start()
    {
        webFrameHandler = GetComponent<WebFrameHandler>();
        webFrameHandler.OnAvatarExport += HandleAvatarLoaded;
        webFrameHandler.OnUserSet += HandleUserSet;
        webFrameHandler.OnUserAuthorized += HandleUserAuthorized;
    }

    private void OnAvatarLoadCompleted(object sender, CompletionEventArgs args)
    {
        if (avatar) Destroy(avatar);
        avatar = args.Avatar;
        if (args.Metadata.BodyType == BodyType.HalfBody)
        {
            avatar.transform.position = new Vector3(0, 1, 0);
        }

        GameObject[] players = GameObject.FindGameObjectsWithTag("Player");
        foreach (GameObject player in players)
        {
            if (player.GetComponent<PhotonView>().IsMine)
                player.GetComponent<PlayerSetup>().SetupLocalPlayer(args.Url);
        }
    }

    private void OnAvatarLoadFailed(object sender, FailureEventArgs args)
    {
        Debug.Log("-----------" + $"Avatar Load failed with error: {args.Message}");
    }

    public void HandleAvatarLoaded(string newAvatarUrl)
    {
        LoadAvatarFromUrl(newAvatarUrl);
    }

    public void HandleUserSet(string userId)
    {
        Debug.Log("-----------" + $"User set: {userId}");
    }

    public void HandleUserAuthorized(string userId)
    {
        Debug.Log("-----------" + $"User authorized: {userId}");
    }

    public void LoadAvatarFromUrl(string newAvatarUrl)
    {
        var avatarLoader = new AvatarObjectLoader();
        avatarUrl = newAvatarUrl;
        avatarLoader.OnCompleted += OnAvatarLoadCompleted;
        avatarLoader.OnFailed += OnAvatarLoadFailed;
        avatarLoader.LoadAvatar(avatarUrl);
    }
}

```

or just add the following to the existing file.
```csharp

    [SerializeField] private string customAvatarUrl = "";
    public void LoadCustom()
    {
        HandleAvatarLoaded(customAvatarUrl);
    }
    
```
     

Here is the full Exception

> JsonSerializationException: Expected string value, instead found: Integer
ReadyPlayerMe.Core.BodyTypeConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, ReadyPlayerMe.Core.BodyType existingValue, System.Boolean hasExistingValue, Newtonsoft.Json.JsonSerializer serializer) (at Library/PackageCache/com.readyplayerme.core@d6867dfb3c/Runtime/Core/Scripts/JsonConverters/BodyTypeConverter.cs:37)
Newtonsoft.Json.JsonConverter`1[T].ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) (at /root/repo/Src/Newtonsoft.Json/JsonConverter.cs:123)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) (at /root/repo/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:2190)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at /root/repo/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:1048)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at /root/repo/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:2433)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at /root/repo/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:502)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at /root/repo/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:309)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at /root/repo/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:202)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at /root/repo/Src/Newtonsoft.Json/JsonSerializer.cs:904)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at /root/repo/Src/Newtonsoft.Json/JsonSerializer.cs:883)
Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at /root/repo/Src/Newtonsoft.Json/JsonConvert.cs:831)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at /root/repo/Src/Newtonsoft.Json/JsonConvert.cs:787)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value) (at /root/repo/Src/Newtonsoft.Json/JsonConvert.cs:720)
ReadyPlayerMe.Core.AvatarMetadata.LoadFromFile (System.String path) (at Library/PackageCache/com.readyplayerme.core@d6867dfb3c/Runtime/Core/Scripts/Data/AvatarMetadata.cs:33)
ReadyPlayerMe.Core.MetadataDownloader.IsUpdateRequired (ReadyPlayerMe.Core.AvatarContext context) (at Library/PackageCache/com.readyplayerme.core@d6867dfb3c/Runtime/Core/Scripts/Operations/MetadataDownloader.cs:131)
ReadyPlayerMe.Core.MetadataDownloader.UpdateContext (ReadyPlayerMe.Core.AvatarContext avatarContext, ReadyPlayerMe.Core.AvatarMetadata metadata) (at Library/PackageCache/com.readyplayerme.core@d6867dfb3c/Runtime/Core/Scripts/Operations/MetadataDownloader.cs:64)
ReadyPlayerMe.Core.MetadataDownloader.Execute (ReadyPlayerMe.Core.AvatarContext context, System.Threading.CancellationToken token) (at Library/PackageCache/com.readyplayerme.core@d6867dfb3c/Runtime/Core/Scripts/Operations/MetadataDownloader.cs:51)
ReadyPlayerMe.Core.OperationExecutor`1[T].Execute (T context) (at Library/PackageCache/com.readyplayerme.core@d6867dfb3c/Runtime/Core/Scripts/Operations/OperationExecutor.cs:48)
ReadyPlayerMe.Core.AvatarObjectLoader.Load (System.String url) (at Library/PackageCache/com.readyplayerme.core@d6867dfb3c/Runtime/Core/Scripts/AvatarObjectLoader.cs:140)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <03bd9b261dff4c2b8b568aca27f561b2>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e8a406da998549af9a2680936c7da25a>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <e8a406da998549af9a2680936c7da25a>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <e8a406da998549af9a2680936c7da25a>:0)

Just before the exception, this is printed to Log
> [Ready Player Me] MetadataDownloader: FullBody metadata loading completed.

Not getting the issue with every model. e.g., 
Issue : https://models.readyplayer.me/65d5ae4662ad266c2e91f3ae.glb
No Issue : https://models.readyplayer.me/64b5494293da602c1d90a0c2.glb

**Comment by ripperdoc** [comment]
We are getting the same issue on 6.0.1, for some models, e.g https://models.readyplayer.me/64ef0b3542c59d7dceb2f468.glb

```
JsonSerializationException: Expected string value, instead found: Integer
ReadyPlayerMe.Core.BodyTypeConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, ReadyPlayerMe.Core.BodyType existingValue, System.Boolean hasExistingValue, Newtonsoft.Json.JsonSerializer serializer) (at ./Library/PackageCache/com.readyplayerme.core@73ec358113/Runtime/Core/Scripts/JsonConverters/BodyTypeConverter.cs:36)
Newtonsoft.Json.JsonConverter`1[T].ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value) (at <761cf2a144514d2291a678c334d49e9b>:0)
ReadyPlayerMe.Core.AvatarMetadata.LoadFromFile (System.String path) (at ./Library/PackageCache/com.readyplayerme.core@73ec358113/Runtime/Core/Scripts/Data/AvatarMetadata.cs:33)
ReadyPlayerMe.Core.MetadataDownloader.IsUpdateRequired (ReadyPlayerMe.Core.AvatarContext context) (at ./Library/PackageCache/com.readyplayerme.core@73ec358113/Runtime/Core/Scripts/Operations/MetadataDownloader.cs:131)
ReadyPlayerMe.Core.MetadataDownloader.UpdateContext (ReadyPlayerMe.Core.AvatarContext avatarContext, ReadyPlayerMe.Core.AvatarMetadata metadata) (at ./Library/PackageCache/com.readyplayerme.core@73ec358113/Runtime/Core/Scripts/Operations/MetadataDownloader.cs:64)
ReadyPlayerMe.Core.MetadataDownloader.Execute (ReadyPlayerMe.Core.AvatarContext context, System.Threading.CancellationToken token) (at ./Library/PackageCache/com.readyplayerme.core@73ec358113/Runtime/Core/Scripts/Operations/MetadataDownloader.cs:51)
ReadyPlayerMe.Core.OperationExecutor`1[T].Execute (T context) (at ./Library/PackageCache/com.readyplayerme.core@73ec358113/Runtime/Core/Scripts/Operations/OperationExecutor.cs:48)
ReadyPlayerMe.Core.AvatarObjectLoader.Load (System.String url) (at ./Library/PackageCache/com.readyplayerme.core@73ec358113/Runtime/Core/Scripts/AvatarObjectLoader.cs:140)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <8f2b770c4a1b401a99ba9ed80a5c09b9>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

**Comment by Thaina** [comment]
I happen to get this error in ios. How can I clear cache?
