### ISSUE TITLE
Avatar not found message when trying to edit an avatar created with a photo

### ISSUE THREAD

**Issue by pbelluzzo** [readyplayerme/rpm-unity-sdk-core#249]
**Describe the bug**
I tried to use the AvatarCreatorWizard scene provided with the SDK as a base to construct my avatar builder, and it works just fine when picking a default avatar and editing, but I'm having issues with the camera feature. When I take the photo, I see the avatar it generated in the scene and the customization screen is there, but when I click on any skin color or accessory, I see the "Updating avatar" banner and then an "Avatar not found" message throws me back to the photo taking screen. Even though I didn't change the code, I tested it directly in the sample scene provided, building it to my android phone, and the error is there too. By debugging this, I found that, apparently, the avatar Id remains empty during the whole process when creating an avatar with phone picture.

**Files**

It's the SDK example.

**To Reproduce**
1. Open the sample scene provided : Assets/Samples/Ready Player Me Core/6.1.0/AvatarCreatorSamples/AvatarCreatorWizard/Scenes
2. Play the scene and follow the wizard until you see the option to create a new avatar. Choose the "Take a Photo!" option;
3. After the avatar being created, you'll see the customization screen. At this point, if you click any accessory, the error occurs.

**Expected behavior**
I expected to be able to edit my avatar after having it initially setup with the camera.

**Screenshots**
![Screenshot_20240321_134111_Cabo_PenPals](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/54654283/2ceb600a-e035-4579-b8d0-4549df016c74)

![Screenshot_20240321_134149_Cabo_PenPals](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/54654283/c134a73e-2c6e-4f6b-83e4-dcc2fc13862a)

![Screenshot_20240321_134251_Cabo_PenPals](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/54654283/48acc9ee-aed0-4556-a94c-9d09e5f60a56)

**Desktop (please complete the following information):**
 - Ready Player Me Core version :: 6.1.0
 - Ready Player Me WebView version :: 2.2.0
 - glTFast version :: 6.0.1
 - Unity Editor version :: 2022.3.20f1
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0]
 - Operating System :: Windows 11
 - Platform :: Android
 
additionally (if significant for the bug):

 - Device: Samsung Galaxy A14
 - OS: Android 13

**Additional context**
Was also tested in other team member phones and editor with webcams, and the problem persisted. I don't know their exact setup.

**Comment by redStriker** [comment]
I am having the same issue. Is there any plans to fix it ?

**Comment by rk132** [comment]
This is fixed in the latest version. Thanks for reporting 👍
