### ISSUE TITLE
Unity got Stuck on Reload/Completing Domain after Import RPM package or switch platform (2022.3.x)

### ISSUE THREAD

**Issue by nickolas52468** [readyplayerme/rpm-unity-sdk-core#279]
**Describe the bug**
After import RPM package from Git on project, has a chance to be stuck on reimport after compiling, startinbg on Realoading Domain phase, then backing to compiling assemblyes starting this loop.
Tested on XR Template Project from Unity Hub, and Universal 3D Core Template from Hub too.

**Files**
[manifest.json](https://github.com/readyplayerme/rpm-unity-sdk-core/files/15391172/manifest.json)
[manifest.json](https://github.com/readyplayerme/rpm-unity-sdk-core/files/15391255/manifest.json)

**To Reproduce**
1. Create a blank project on the informed version (which can be XR template or URP template as well)
2. Import RPM core package (tested on core 6.0 and above)
3. in case the bug doesn´t happen, try to switch platform to Windows Server, for exemple.

**Expected behavior**
After the project´s compilation, Unity will try to finalize but aparently RPM package makes something that stuck for a while on Reload Domain, then restart the process of recompiling, and this keeps forever....

**Desktop (please complete the following information):**
 - Ready Player Me Core version: 6.0.0, 6.2.3, 6.2.4
 - Ready Player Me WebView version default
 - glTFast version : 6.0.1
 - Unity Editor version 2022.3.24, 2022.3.29
 - Render Pipeline and version Universal Render Pipeline: 14.0.11
 - Operating System Windows
 - Platform: Windows Player, Windows Server

**Comment by nickolas52468** [comment]
looks like the cause is around the ReadyPlayerMe.Core.Editor.ModuleInstaller class;
Apparently the 'DelayCreateCoreSettings' keeps being called every time.
i added a unzipped version of the release on the Asset folder, and removed the attribute '[InitializeOnLoad]' of this class for now.
i´m not sure why the problem is happening, but... that was the workarround here.

**Comment by HarrisonHough** [comment]
Did you have the define symbol
`READY_PLAYER_ME` in your player settings (for each target platform) ? 
It should get auto added after installation and once added it should prevent it from reinstalling 
![image](https://github.com/readyplayerme/rpm-unity-sdk-core/assets/7085672/fed23060-bcda-461f-8b17-01244df1f192)

**Comment by nickolas52468** [comment]
Yes, i Check it, and as a switch to Server Platform starts to inifnity realod .

**Comment by nickolas52468** [comment]
When installed this methos runs as expected, but as soon as i change platform to server.... it´s like it never imports and settups RPM opn projet before.
