### ISSUE TITLE
Avatar Creator Wizard Sample back button not functional on first screen

### ISSUE THREAD

**Issue by ibytergj** [readyplayerme/rpm-unity-sdk-core#282]
**Describe the bug**
When you start the Avatar Creator Wizard sample, the back button is enabled. If you click on it, then you get the following error message
InvalidOperationException: Stack empty.

**To Reproduce**
1. Setup new Unity project with RPM Core files 6.2.4
2. Install Avatar Creator Wizard Example
3. Press play 
4. Click on back button in scene
5. See error in console

**Expected behavior**
At a minimum I think the back button should be disabled at the start for the demo.

When the Avatar Creator is integrated into an app what would be really helpful for developers is to have an Exit state configured, where we can register for a call back and cleanup/restore our app to the state it was before calling the Avatar creator.

That state could be triggered when the back button is clicked when at the starting state.

**Desktop (please complete the following information):**
 - Ready Player Me Core version : 6.2.4
 - Ready Player Me WebView version N/A
 - glTFast version - 6.0.1
 - Unity Editor version [e.g. 2021.2.1f1] - 2022.3.30f1
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0] - Builtin
 - Operating System [e.g. Windows, Mac, Linux ] - Windows 10
 - Platform: [e.g. Editor , Windows Player, iOS] - Editor

**Comment by HarrisonHough** [comment]
this should be fixed in latest release 6.3.0
