### ISSUE TITLE
AvatarCreatorWizard sample ignores shader settings in AvatarConfig

### ISSUE THREAD

**Issue by krzys-h** [readyplayerme/rpm-unity-sdk-core#287]
**Describe the bug**
I was trying to change the shader used for the avatars to the Standard shader to better match the visual look of my app, but it seems that while the shader settings work when using `AvatarObjectLoader` manually, they are ignored in the `InCreatorAvatarLoader` code path, which results in them being ignored during avatar editing.

**To Reproduce**
1. Import the SDK and the AvatarCreatorWizard sample
2. In the `AvatarCreatorSelection` component, change the `inCreatorConfig` property to the configuration found in `Packages/Ready Player Me Core/Runtime/Core/Configurations/Avatar Config Standard Shader.asset`
3. Run the sample
4. Notice that the loaded avatar still uses the `glTF/PbrMetallicSmoothness` shader. Any other avatar configuration seems to apply properly.

**Expected behavior**
The shader is switched to the `Standard` shader as requested.

**Desktop (please complete the following information):**
 - Ready Player Me Core version: 6.2.4
 - Ready Player Me WebView version: (not used)
 - glTFast version: 6.0.1
 - Unity Editor version: 2021.3.38f1
 - Render Pipeline and version: Standard
 - Operating System: Windows
 - Platform: doesn't matter

**Additional context**
It seems that `AvatarProcessor.SetShader` is passed a null `AvatarConfig`, because `InCreatorAvatarLoader` does not set it in `AvatarContext.AvatarConfig`. Most other parameters only influence the SDK request, this is likely the only one that matters for postprocessing the downloaded avatar, which is likely why it was missed here.

**Comment by HarrisonHough** [comment]
Hey thanks for reporting. 
We recently made a fix for this and it will be included in the next release 
https://github.com/readyplayerme/rpm-unity-sdk-core/pull/286

The release should be live early next week at the latest.

**Comment by HarrisonHough** [comment]
this should be fixed now in 6.3
