### ISSUE TITLE
VoiceHandler memory access out of bounds on WebGL

### ISSUE THREAD

**Issue by baaskoen** [readyplayerme/rpm-unity-sdk-core#320]
**Describe the bug**
When the assigned audio clip in the VoiceHandler script is played in the browser, the app will crash as soon as the audio stops playing. Happens on all browsers. The audio clip will play just fine, the exception is thrown when it ends.

**Files**

I'm using an empty project with no modifications, only an imported character and a tiny mp3 file.

**To Reproduce**
1. Import a RPM character
2. Add the VoiceHandler component
3. Set AudioProvider to "AudioClip" on that component
4. Assign a random audio clip (I had the same error on different audio files)
5. Build to WebGL and play the audio (via canvas button for example, or play on awake)

**Expected behavior**
There should be no memory exception. When playing the audio manually without the VoiceHandler on a differen unity node produces no error.

**Screenshots**

![Screenshot 2024-10-02 at 09 56 14](https://github.com/user-attachments/assets/6656425c-0916-43bf-880e-2aa98e44a3c8)

![Screenshot 2024-10-02 at 09 56 31](https://github.com/user-attachments/assets/bcd43835-f224-4716-b01c-4d8df2203252)

**Desktop (please complete the following information):**
 - Ready Player Me Core version: 7.2.0
 - Ready Player Me WebView version: ?
 - glTFast version: 6.0.1
 - Unity Editor version [e.g. 2021.2.1f1]: 2022.3.40f1
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0]: URP 14.0.11
 - Operating System [e.g. Windows, Mac, Linux ]: Any browser.
 - Platform: [e.g. Editor , Windows Player, iOS]: Any browser.
 
additionally (if significant for the bug):

- Any browser running on Macbook Pro

**Comment by baaskoen** [comment]
I locally modified the `VoiceHandler` @ `GetAmplitude method so that it compares the timeSamples:

```
private float GetAmplitude()
{
    if (CanGetAmplitude)
    {
        var amplitude = 0f;

        if (AudioSource.timeSamples + AUDIO_SAMPLE_LENGTH > AudioSource.clip.samples)
        {
            Debug.LogError("Requested samples exceed available samples in the clip.");
            return 0f;
        }

        AudioSource.clip.GetData(audioSample, AudioSource.timeSamples);

        foreach (var sample in audioSample)
        {
            amplitude += Mathf.Abs(sample);
        }

        return Mathf.Clamp01(amplitude / audioSample.Length * AMPLITUDE_MULTIPLIER);
    }

    return 0;
}
```

This prevents the app from crashing, although it will still log the error multiple times.

**Comment by rk132** [comment]
Thanks for reporting, we will look into it.

**Comment by HarrisonHough** [comment]
This should be fixed now 
https://github.com/readyplayerme/rpm-unity-sdk-core/releases/tag/v7.3.0
