### ISSUE TITLE
Failed to import glb model from bytes. Unity RPM SDK 2.0.0

### ISSUE THREAD

**Issue by JanFromNaomiAnimation** [readyplayerme/rpm-unity-sdk-core#42]
**Describe the bug**
Not able to import model (iOS platform in runtime as same as in Unity Editor via Ready Player Me/Avatar Loader)

**Files**
Tested avatar e.g.:
https://models.readyplayer.me/63db9a0372f63b7131e0fbc5.glb

**To Reproduce**
1. Go to 'Unity Editor -> Ready Player Me (in top menu) -> Avatar Loader
2. add avatar URL into "Avatar URL or shortcode"
3. tap on "Load Avatar into the Current Scene"

**Expected behavior**
Model will be loaded into current scene

**Desktop (please complete the following information):**
 - Ready Player Me Core version 0.1.1
 - Ready Player Me Avatar Loader version 0.1.1
 - Ready Player Me WebView version 0.1.0
 - glTFast version 5.0.0 (added as source files directly into project - because it was not possible to install it via packages)
 - Unity Editor version 2021.3.15f1
 - Render Pipeline and version URP 12.1.8
 - Operating System macOS Ventura 13.2
 - Platform: Editor, iOS
 
**Additional context**

stack trace: (from import in Unity editor)

Asset import failed, "Assets/Ready Player Me/Avatars/63db9a0372f63b7131e0fbc5/63db9a0372f63b7131e0fbc5.glb" > NullReferenceException: Object reference not set to an instance of an object
GLTFast.Materials.ShaderGraphMaterialGenerator.GenerateDefaultMaterial (System.Boolean pointsSupport) (at Assets/Plugins/glTFast-5.0.0/Runtime/Scripts/Material/ShaderGraphMaterialGenerator.cs:179)
GLTFast.Materials.MaterialGenerator.GetDefaultMaterial (System.Boolean pointsSupport) (at Assets/Plugins/glTFast-5.0.0/Runtime/Scripts/Material/MaterialGenerator.cs:239)
GLTFast.GltfImport.GetDefaultMaterial () (at Assets/Plugins/glTFast-5.0.0/Runtime/Scripts/GltfImport.cs:698)
GLTFast.GameObjectInstantiator.AddPrimitive (System.UInt32 nodeIndex, System.String meshName, UnityEngine.Mesh mesh, System.Int32[] materialIndices, System.UInt32[] joints, System.Nullable`1[T] rootJoint, System.Single[] morphTargetWeights, System.Int32 primitiveNumeration) (at Assets/Plugins/glTFast-5.0.0/Runtime/Scripts/GameObjectInstantiator.cs:294)
GLTFast.GltfImport+<>c__DisplayClass117_0.<InstantiateSceneInternal>g__PopulateHierarchy|2 (System.UInt32 nodeIndex, System.Nullable`1[T] parentIndex) (at Assets/Plugins/glTFast-5.0.0/Runtime/Scripts/GltfImport.cs:2331)
GLTFast.GltfImport+<>c__DisplayClass117_0.<InstantiateSceneInternal>g__IterateNodes|0 (System.UInt32 nodeIndex, System.Nullable`1[T] parentIndex, System.Action`2[T1,T2] callback) (at Assets/Plugins/glTFast-5.0.0/Runtime/Scripts/GltfImport.cs:2261)
GLTFast.GltfImport+<>c__DisplayClass117_0.<InstantiateSceneInternal>g__IterateNodes|0 (System.UInt32 nodeIndex, System.Nullable`1[T] parentIndex, System.Action`2[T1,T2] callback) (at Assets/Plugins/glTFast-5.0.0/Runtime/Scripts/GltfImport.cs:2267)
GLTFast.GltfImport.InstantiateSceneInternal (GLTFast.Schema.Root gltf, GLTFast.IInstantiator instantiator, System.Int32 sceneId) (at Assets/Plugins/glTFast-5.0.0/Runtime/Scripts/GltfImport.cs:2426)
GLTFast.GltfImport.InstantiateSceneAsync (GLTFast.IInstantiator instantiator, System.Int32 sceneIndex, System.Threading.CancellationToken cancellationToken) (at Assets/Plugins/glTFast-5.0.0/Runtime/Scripts/GltfImport.cs:599)
GLTFast.Utils.AsyncHelpers+<>c__DisplayClass1_0`1[T].<RunSync>b__0 (System.Object _) (at Assets/Plugins/glTFast-5.0.0/Editor/Scripts/AsyncHelpers.cs:66)
Rethrow as AggregateException: AsyncHelpers.Run method threw an exception. (Object reference not set to an instance of an object)
GLTFast.Utils.AsyncHelpers+ExclusiveSynchronizationContext.BeginMessageLoop () (at Assets/Plugins/glTFast-5.0.0/Editor/Scripts/AsyncHelpers.cs:122)
GLTFast.Utils.AsyncHelpers.RunSync[T] (System.Func`1[TResult] task) (at Assets/Plugins/glTFast-5.0.0/Editor/Scripts/AsyncHelpers.cs:73)
GLTFast.Editor.GltfImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Assets/Plugins/glTFast-5.0.0/Editor/Scripts/GltfImporter.cs:158)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at /Users/bokken/build/output/unity/unity/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)

**Comment by HarrisonHough** [comment]
I believe this is an issue with a shader variant missing. 
In particular you just need to add this variant 
![image](https://user-images.githubusercontent.com/7085672/217138024-8675f930-c30f-4fd5-8bd3-b6f26bdc60e9.png)
And then ensure that this shadervariants collection is set in the Graphics>Preloaded shaders setting
![image](https://user-images.githubusercontent.com/7085672/217137809-e1d3288e-56aa-4072-9da6-b841c3e3efbc.png)
This will be fixed in the next release of Avatar Loader. 
But thanks for letting us know.

**Comment by rYuuk** [comment]
Will be fixed in next release.

**Comment by Uralstech** [comment]
Hi! This issue still occurs when a project is converted from the built-in RP to URP. Maybe this step can be added in the Unity FAQs?
