### ISSUE TITLE
Corrupted model

### ISSUE THREAD

**Issue by JanFromNaomiAnimation** [readyplayerme/rpm-unity-sdk-core#49]
**Describe the bug**
Model issues -> material and geometry. Looks like there is problem with material and geometry in case of one particular model. 

**Files**
Avatar: https://models.readyplayer.me/63f145159233b3995d697910.glb

**To Reproduce**
1. Open RPM webview
2. create famela full body character and find the particular clothes variant
3. see the noise when user is rotating with model
4. save avatar, check thumbnail
5. import into unity -> see geometry and material issues

**Expected behavior**
Model has correct geometry and no flicking material

**Screenshots**

On device (ipad air 2021)

![image](https://user-images.githubusercontent.com/124244732/219936194-638e9600-8cea-4f0f-8fe8-d5e18b28ed5e.png)

![rpme_01](https://user-images.githubusercontent.com/124244732/219936214-3d1ae488-aa85-4cd7-b7e1-2e1e07bac06f.PNG)

![image](https://user-images.githubusercontent.com/124244732/219936268-b0c64a42-ed95-4db7-96ce-88906152b09a.png)

https://user-images.githubusercontent.com/124244732/219936219-99a403f3-9897-4509-b97c-5be3135ac5ea.mov

In Unity editor:

![image](https://user-images.githubusercontent.com/124244732/219936424-2072e2a7-7b9f-45b4-9889-1cad4ef37c78.png)

**Desktop (please complete the following information):**
 - Ready Player Me Core version 1.0.0
 - Ready Player Me Avatar Loader version 1.0.0
 - Ready Player Me WebView version 1.0.0
 - glTFast version 5.0.0
 - Unity Editor version 2021.3.15f
 - Render Pipeline and version 
 - Operating System Mac OS, Ventura 13.2
 - Platform: Editor, iOS
 
additionally (if significant for the bug):

 - Device: iPad Air (4th generation)
 - OS: 15.6

**Comment by srcnalt** [comment]
I am also able to reproduce. There is a material-related bug in this outfit. Reported to the art team.

**Comment by HarrisonHough** [comment]
Art team has updated this outfit. 
It should be fixed now, you will need to update the avatar (by changing outfits to trigger a rebake of the asset) or create a new one to get the effect.
