### ISSUE TITLE
The installation is failing using the package manager - missing folder

### ISSUE THREAD

**Issue by ManjitBedi** [readyplayerme/rpm-unity-sdk-core#54]
**Describe the bug**

I am doing a new install of the SDK using the Unity package manager.  

**Files**

Attach or link to .glb files or avatar URL that trigger the bug. 

In addition, make sure to run those files through the example scenes first. If you encounter errors or warnings, try to make sure they are not responsible for the issue.

> Note: You have to ZIP archive them first in order for GitHub to accept the upload.
If your files are confidential:

- Try to create a similar, but intellectual-property-free Unity example project or build that reproduces the bug in the same way (so any community member can have a look)
- Otherwise, still create this issue and send the files (or a link to them) discretely via email

**To Reproduce**
1. Add the RPM SDK from the package manager in Unity
2. The install will hang on an error:

```Parent directory must exist before creating asset at Assets/Ready Player Me/Resources/Settings/CoreSettings.asset.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
ReadyPlayerMe.Core.CoreSettingsHandler:CreateCoreSettings () (at Library/PackageCache/com.readyplayerme.core@4bccdb4898/Runtime/CoreSettingsHandler.cs:51)
ReadyPlayerMe.Core.CoreSettingsHandler:get_CoreSettings () (at Library/PackageCache/com.readyplayerme.core@4bccdb4898/Runtime/CoreSettingsHandler.cs:21)
ReadyPlayerMe.Core.SDKLogger:IsLoggingEnabled () (at Library/PackageCache/com.readyplayerme.core@4bccdb4898/Runtime/Logger/SDKLogger.cs:25)
ReadyPlayerMe.Core.SDKLogger:.cctor () (at Library/PackageCache/com.readyplayerme.core@4bccdb4898/Runtime/Logger/SDKLogger.cs:20)
ReadyPlayerMe.Core.Editor.ModuleInstaller:AddModuleRequest (string) (at Library/PackageCache/com.readyplayerme.core@4bccdb4898/Editor/Module Management/ModuleInstaller.cs:111)
ReadyPlayerMe.Core.Editor.ModuleInstaller:InstallModules () (at Library/PackageCache/com.readyplayerme.core@4bccdb4898/Editor/Module Management/ModuleInstaller.cs:87)
ReadyPlayerMe.Core.Editor.ModuleInstaller:OnRegisteredPackages (UnityEditor.PackageManager.PackageRegistrationEventArgs) (at Library/PackageCache/com.readyplayerme.core@4bccdb4898/Editor/Module Management/ModuleInstaller.cs:47)
UnityEditor.PackageManager.Events:InvokeRegisteredPackages (UnityEditor.PackageManager.PackageRegistrationEventArgs)
```

**Expected behavior**
The install should complete. 

**Screenshots**
<img width="1024" alt="Screenshot 2023-03-10 at 12 46 25 PM" src="https://user-images.githubusercontent.com/2837803/224425589-b8aa96c3-36d9-4ab2-af7f-27837cb0b828.png">

**Desktop (please complete the following information):**
 - Ready Player Me Core version - na
 - Ready Player Me Avatar Loader version - na
 - Ready Player Me WebView version - na
 - glTFast version - na
 - Unity Editor version [e.g. 2021.2.1f1] - Unity 2021 LTS
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0]
 - Operating System [e.g. Windows, Mac, Linux ] MacOS
 - Platform: [e.g. Editor , Windows Player, iOS] - na
 
additionally (if significant for the bug):

 - For WebGL: Browser [e.g. stock browser, safari]

**Additional context**

**Comment by HarrisonHough** [comment]
What was the URL you copy and pasted into the Package manager via the "Add package from git URL" option? 
For example, the correct one is 
https://github.com/readyplayerme/rpm-unity-sdk-core.git#v1.0.0

**Comment by ManjitBedi** [comment]
Yes, I used that URL.

**Comment by HarrisonHough** [comment]
Can you check the permissions of the Unity Projects `Assets` folder? 
You might need to set them to Read & Write before importing trying to reimport the package.

**Comment by ManjitBedi** [comment]
The permissions for the logged in user were set to read write in the assets folder.  I changed the permissions to allow everyone read write access. The problem still occurs.

Here is the editor log - I removed some personal information.

[Unity editor log.txt](https://github.com/readyplayerme/rpm-unity-sdk-core/files/10959732/Unity.editor.log.txt)

**Comment by srcnalt** [comment]
Can you try without the version number at the end of the URL `#v1.1.0` try with the git URL alone. 
https://github.com/readyplayerme/rpm-unity-sdk-core.git

**Comment by bollerdominik** [comment]
Same issue. Also with #v1.0.0.

0.1.1. seems to work

**Comment by xilanxiaoge** [comment]
> What was the URL you copy and pasted into the Package manager via the "Add package from git URL" option? For example, the correct one is https://github.com/readyplayerme/rpm-unity-sdk-core.git#v1.0.0

I can't understand why it is so difficult for developer to install it? it takes mine 3-5 hours to install it.

**Comment by srcnalt** [comment]
`#version` work only if the git repository has a branch named version, which is not the case for this repository. `main` branch is always the latest. There was an issue in the readme file and documentation which is fixed now. Closing the issue.
