### ISSUE TITLE
Unity Add Package from git URL failure.

### ISSUE THREAD

**Issue by Geethanimal** [readyplayerme/rpm-unity-sdk-core#57]
### Discussed in https://github.com/readyplayerme/rpm-unity-sdk-core/discussions/55

<div type='discussions-op-text'>

<sup>Originally posted by **Geethanimal** March 15, 2023</sup>
I tried to add this package to unity using [https://github.com/readyplayerme/rpm-unity-sdk-core.git#v1.0.0 ](https://github.com/readyplayerme/rpm-unity-sdk-core.git#v1.0.0 ) this URL that provided by official documentation. But an error occurs.

The error is below. 

[Package Manager Window] Error adding package: https://github.com/readyplayerme/rpm-unity-sdk-core.git#v1.0.0.
Unable to add package [https://github.com/readyplayerme/rpm-unity-sdk-core.git#v1.0.0]:
  Error when executing git command. fatal: update_ref failed for ref 'HEAD': cannot update ref 'refs/heads/master': trying to write non-commit object c6abc7525bab6ab7f2b3e7e558d12789c8c3788f to branch 'refs/heads/master'
  
 I also used this URL [https://github.com/readyplayerme/Unity-core.git](https://github.com/readyplayerme/Unity-core.git) that is provided in the README of the repo but it takes a long time and not working.
  
 How can I resolve this error and install this package in unity?</div>

**Comment by PavelKlymentenkoSA** [comment]
Did you try to add packages manually into **manifest.json** file? 
You can find **manifest.json** file under the **Packages** folder in Unity project.
Take a try to add after the package (This is the latest 1.1.0 version):
```
"com.atteneder.gltfast": "https://github.com/atteneder/glTFast.git#v5.0.0",
"com.readyplayerme.avatarloader": "https://github.com/readyplayerme/rpm-unity-sdk-avatar-loader.git#v1.1.0",
"com.readyplayerme.core": "https://github.com/readyplayerme/rpm-unity-sdk-core.git#v1.1.0",
"com.readyplayerme.webview": "https://github.com/readyplayerme/rpm-unity-sdk-webview.git#v1.1.0"
```

**Comment by srcnalt** [comment]
Hi @Geethanimal can you try fetching from the main branch directly using https://github.com/readyplayerme/rpm-unity-sdk-core.git
`Unity-core` is the former name of the package which is not used. I'll see where in the readme it is and will remove it.

**Comment by onglette** [comment]
> Did you try to add packages manually into **manifest.json** file? You can find **manifest.json** file under the **Packages** folder in Unity project. Take a try to add after the package (This is the latest 1.1.0 version):
> 
> ```
> "com.atteneder.gltfast": "https://github.com/atteneder/glTFast.git#v5.0.0",
> "com.readyplayerme.avatarloader": "https://github.com/readyplayerme/rpm-unity-sdk-avatar-loader.git#v1.1.0",
> "com.readyplayerme.core": "https://github.com/readyplayerme/rpm-unity-sdk-core.git#v1.1.0",
> "com.readyplayerme.webview": "https://github.com/readyplayerme/rpm-unity-sdk-webview.git#v1.1.0"
> ```

I installed using the urls from github above and had these errors when opening my project

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/GLTFDeferAgent.cs(1,7): error CS0246: The type or namespace name 'GLTFast' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/Operations/GltFastAvatarImporter.cs(5,7): error CS0246: The type or namespace name 'GLTFast' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/Operations/GltFastGameObjectInstantiator.cs(1,7): error CS0246: The type or namespace name 'GLTFast' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/Operations/GltFastGameObjectInstantiator.cs(2,7): error CS0246: The type or namespace name 'GLTFast' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/GLTFDeferAgent.cs(6,11): error CS0246: The type or namespace name 'IDeferAgent' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/Operations/GltFastGameObjectInstantiator.cs(10,50): error CS0246: The type or namespace name 'GameObjectInstantiator' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/Operations/GltFastGameObjectInstantiator.cs(23,30): error CS0115: 'GltFastGameObjectInstantiator.AddPrimitive(uint, string, Mesh, int[], uint[], uint?, float[], int)': no suitable method found to override

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/Operations/GltFastGameObjectInstantiator.cs(13,13): error CS0246: The type or namespace name 'IGltfReadable' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/Operations/GltFastGameObjectInstantiator.cs(15,13): error CS0246: The type or namespace name 'ICodeLogger' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.readyplayerme.avatarloader@ba178d9f8a/Runtime/Operations/GltFastGameObjectInstantiator.cs(16,13): error CS0246: The type or namespace name 'InstantiationSettings' could not be found (are you missing a using directive or an assembly reference?)

Hope this helps
