### ISSUE TITLE
Where is the version 2.0 SDK please?

### ISSUE THREAD

**Issue by devzhuchuanbo** [readyplayerme/rpm-unity-sdk-core#61]

**Comment by srcnalt** [comment]
Hi @devzhuchuanbo SDK v2 is now a set of modules hosted in multiple repositories, and this repo, rpm-unity-sdk-core, helps you install all the necessary components. You can follow the guide in the [README.md](https://github.com/readyplayerme/rpm-unity-sdk-core/blob/main/README.md) for importing it into Unity.

**Comment by devzhuchuanbo** [comment]
Tks, but I followed it  and the version is still v1.1

**Comment by devzhuchuanbo** [comment]
And your latest version is also shown as v1.1
![image](https://user-images.githubusercontent.com/20489157/231693498-f6e8de1f-44ae-4922-8fd8-385f32072613.png)
![image](https://user-images.githubusercontent.com/20489157/231693639-2b49e1d7-4db7-4520-9463-a83ed5180582.png)

**Comment by srcnalt** [comment]
Now SDK v2, or let's say the RPM Unity SDK consists of 4 components. Core, Avatar Loader, WebView, glTFast, and each of these modules have their own version, in this case, the Core module which is responsible for module installment and management has its own version number, which has latest version 1.1.0

**Comment by devzhuchuanbo** [comment]
Okay, thanks Sercan. This has been bugging me for half a day. I can close this issue now.
